### ISSUE TITLE
Download by Res

### ISSUE THREAD

**Issue by cmanjunathan45** [shubham1710/Youtube-downloader#2]
How to Download videos by resolution 
can we use **get_by_res()** .
when I use **get_by_res()**, 
**AttributeError: 'StreamQuery' object has no attribute 'get_by_res'**
this error occurs....

**Comment by shubham1710** [comment]
It is get_by_resolution() and not get_by_res().
Refer to the official documents of Pytube here. You would get all functionalities here.
https://python-pytube.readthedocs.io/en/latest/api.html

**Comment by cmanjunathan45** [comment]
Ok sir
