### ISSUE TITLE
valueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by mchopan** [shubham1710/Youtube-downloader#4]
![JPEG_20200729_150710](https://user-images.githubusercontent.com/28682155/88786735-825fff00-d1b0-11ea-86d0-05b08ee08e93.jpg)
![Uploading JPEG_20200729_150749.jpg…]()

**Comment by shubham1710** [comment]
Yes, this was an issue as Youtube changed their Javascript so now this no longer works.

So, you need to install pytubeX to fix this issue. Its the new pytube3 update.
Code will remain same.

Just do:
pip install pytubeX
